version: '3.7'

services:
  reabot_server:
    depends_on:
      - db
    restart: always
    build:
      context: .
      target: development
    ports:
      - '8080:3000'
    command: yarn start:dev
    env_file:
      - '.env'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - webnet
  db:
    image: mongo
    container_name: db_mongo
    ports:
      - '27018:27017'
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
