version: '3.7'

services:
  reabot_server_dev:
    restart: always
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    command: yarn start:dev
    environment:
      - NODE_ENV=development
      - DB_URI=${DB_URI}
    env_file:
      - '.env'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
