version: '3.7'

services:
  reabot_server_prod:
    build:
      context: .
      target: production
    ports:
      - '3000:3000'
    command: yarn start:prod
    environment:
      - NODE_ENV=production
      - DB_URI=${DB_URI}
    env_file:
      - '.env'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
